---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# Overview - Open Science in the public sector

This repository contains various materials relevant for discussions and presentations on the topic of Open Science and Open Source systems used in the public sector.

- The 23rd is a symposium with several presentations and discussions.

- The 24th and 25th is a two day course in the use of Open Source tools for biodiversity analysis.

## The symposium on the 23rd

The symposium about Open Source Systems in the Public Sector held on the Monday January 23, 2017 at the Swedish Museum of Natural History, Stockholm, Sweden is announced here:

http://www.nrm.se/english/researchandcollections/symposiumopensourcesystems.os2017.html

The programme is here with the details:

http://www.nrm.se/english/researchandcollections/symposiumopensourcesystems/program.9003769.html

After lunch there is one hour planned with some specific presentations (13:15 - 14:15):

- 13:15 Open Source techniques in support of Biodiversity data; examples from Atlas of Living Australia (ALA)

- 13:35 R and Open Science, Scott Chamberlain, rOpenSci

- 13:55 R tools for Biodiversity Informatics, Markus Skyttner, Swedish Museum of Natural History

## The course on the 24th and 25th

This two day course is announced here:

http://www.nrm.se/english/researchandcollections/courseopensourcetoolsforbiodiversityanalysis.9003870.html

The schedule is described here:

http://blog.dina-web.net/os-2017/course.html#schedule

### Presenters

Presentations are primarily by:

- Scott Chamberlain, ROpenSci
- Ben Raymond, [ACE CRC](http://acecrc.org.au/)
- Alejandro Ruete, [Swedish University of Agricultural Sciences] (http://www.slu.se/en/)
- Markus Skyttner, Swedish Museum of Natural History
- Alexander Zizka, Gothenburg University

### Topics to be presented

Topics include:

- R for scientific computation and biodiversity analysis
- rOpenSci and R packages for biodiversity analysis
- Ignorance scores for primary biodiversity data
- Mirroreum and EU-BON R packages
- Atlas of Living Australia and ALA4R
	- a brief overview of the ALA and the full APIs
	- the ALA4R package and the API subset that it covers
	- some use case examples
- speciesgeocodeR and sampbias R packages

### Exercises 

TODO: add more details about exercises and demonstrations here

# Resources

- ROpenSci - "Fostering open science and open data with R" at https://ropensci.github.io/ambassador-packet/slides/#ropensci
- Nordic Open Science materials from Finland at http://openscience.fi/initiatives
